application: btc-lotto
version: 1
runtime: python
api_version: 1

handlers:

- url: /btcadmin
  script: btcadmin.py
  login: admin

- url: /
  script: lotto.py

- url: /new
  script: lotto.py
  login: admin

- url: /winner
  script: lotto.py
  login: admin

- url: /countdown.js
  static_files: static/countdown.js
  upload: static/countdown.js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

